context:
  site:
    title: Culturebook
    handle: culturebook
    description: Culturebook's an entire web-based platform suitable for handheld and desktop devices where users can browse, engage and interact with our cultural heritage from paintings and exhibits to user contributions such as audio narrative, podcasts, video and multi-lingual translations.
    url: https://culturebook.co.uk
    theme_color: "#b11f29"
