variants:
- name: default
  context:
    items:
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
- name: authors
  context:
    items:
    - author: Drew McLellan
    - author: Brian Suda
    - author: Anna Debenham
    - author: Owen Gregory
